### ISSUE TITLE
Using this plugin in ionic2+

### ISSUE THREAD

**Issue by eyas2n** [MenelicSoftware/cordova-plugin-brother-label-printer#10]
I'm trying to integrate this into an ionic2 app with no luck.
Any suggestion/guidance.
I used
https://www.joshmorony.com/using-cordova-plugins-in-ionic-2-with-ionic-native/

**Comment by arcadius** [comment]
Not sure whether this is still valid @eyas2n 
Please let me know if it's still an issue

Please install the plugin using
`ionic plugin add cordova-plugin-brother-label-printer --save`
