### ISSUE TITLE
Ability to lookup printer at runtime

### ISSUE THREAD

**Issue by arcadius** [MenelicSoftware/cordova-plugin-brother-label-printer#2]
Currently, the printer name/type has to be specified in code.
We want to pass the printer name etc as parameter to ```printViaNetwork()``` and ```printViaBluetooth()```

**Comment by gordol** [comment]
You can use the Printer().getNetPrinters() method to find all printers on the network, but you must know the model name in advance... This is unfortunately how brother designed their API. You can of course keep a list of many model names, and then iterate them all to find all the printers of various types.

You can also do direct printing via USB, but again, you need to know the model type in advance.

**Comment by gordol** [comment]
Instead of passing the printer model as a parameter, it would probably be best to set it from another method, so all the methods in the printer library that require the model can reference it globally, without it needing to be passed around constantly.

**Comment by arcadius** [comment]
Thank you very much for the input @gordol .
Most apporeciated

**Comment by arcadius** [comment]
fixed in https://github.com/MenelicSoftware/cordova-plugin-brother-label-printer/pull/3
