### ISSUE TITLE
Cannot find Bluetooth Printer on Android 

### ISSUE THREAD

**Issue by DorianLovera** [MenelicSoftware/cordova-plugin-brother-label-printer#21]
Hello and thank you for your work on this plugin so far. 

I am currently facing a critical issue with the Bluetooth on this plugin. After calling  `findNetworkPrinters()` or `findBluetoothPrinters()`, the method returns an empty array : [ ]

**What I have tested so far:**

- I have tested discovery through Wifi and it works well by returning the Printer's interface. 

- I tried to hardcode the Bluetooth interface using the Printer's mac adress but the `setPrinter()` method returns the following:  _An error occurred while trying to set the printer._

**Configuration** 

Printer : QL-820NWB
Mobile Phone : Google Pixel 1 - Android 10 
Framework : Ionic 4 

I really hope that someone can help me resolve this issue. Can this be linked to a depreceated SDK or a missing authorization for Bluetooth in my config.xml ? 

Thank you for your support

**Comment by DorianLovera** [comment]
I have discovered the following commented lines in the plugin config.xml : 

`<uses-permission android:name="android.permission.BLUETOOTH" android:required="false" />
                        <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:required="false" />`

I will try to uncomment them tomorrow at work, test and keep you updated.

**Comment by DorianLovera** [comment]
My answer above solved the problem ! I hope that this issue helps someone :)

**Comment by josiaho** [comment]
Hey Dorian! Did you have to configure or add any permissions in the plugin or AndroidManifest to get WiFi connected printers to show up? I happen to also be testing a Pixel 1 with Android 10, but findPrinters is returning an empty array.

On iOS the printer shows up and  prints great - so I'm thinking it's something in Android permissions rather than my network.

Thanks!
