### ISSUE TITLE
I've created a pull request which allows QL1100 with W103H164 paperSize + bluetooth permission 

### ISSUE THREAD

**Issue by LimitTech** [MenelicSoftware/cordova-plugin-brother-label-printer#31]
It works with my printer. Please see: #30 

Note: It would be fine if the AndroidManifest add Bluetooth permission as well. I haven't added it because I'm not sure why it isn't included:

    <platform name="android">
        <allow-intent href="market:*" />
        <config-file parent="/manifest" target="AndroidManifest.xml">
            <uses-permission android:name="android.permission.BLUETOOTH" />
            <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
        </config-file>
    </platform>

**Comment by arcadius** [comment]
Feel free to raise a PR if you have tested it and it's working for you

**Comment by arcadius** [comment]
Thanks @LimitTech
