### ISSUE TITLE
Empty array returned with QL-820NWB and iOS 14+

### ISSUE THREAD

**Issue by cpgb85** [MenelicSoftware/cordova-plugin-brother-label-printer#33]
This worked perfectly on the previous iOS version. It no longer works as of 14 and returns an empty array.  On a previous post someone mentioned adding Bonjour services which didn't work and it wasn't explained where to add them.

**Comment by robr2112** [comment]
You need to add them to the Info.plist.

![iOS14_LocalNetwork_infoPlist](https://user-images.githubusercontent.com/5835002/109569362-913fc480-7aa5-11eb-9aae-6afccee39820.png)

**Comment by cpgb85** [comment]
My xcode looks nothing like this.  I don't see a custom iOS Target Properties.

**Comment by cpgb85** [comment]
> You need to add them to the Info.plist.
> 
> ![iOS14_LocalNetwork_infoPlist](https://user-images.githubusercontent.com/5835002/109569362-913fc480-7aa5-11eb-9aae-6afccee39820.png)

This worked for me! Thank you.
