### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by josiaho** [MenelicSoftware/cordova-plugin-brother-label-printer#35]
Hello, I'm getting the following error when attempting to add the plugin to my project:

Failed to fetch plugin git+https://github.com/MenelicSoftware/cordova-plugin-brother-label-printer.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Could not determine package name from output:
audited 69 packages in 34.607s

Thoughts? Thanks!

**Comment by dave-carner** [comment]
@josiaho Did you recently update NPM to latest? I attempted to install this plugin after updating NPM to `v7.7.0` and got the same issue. I downgraded NPM back to `v6.14.3` and was able to install the plugin.

**Comment by josiaho** [comment]
Thanks for the tip - I'll check it out!
