### ISSUE TITLE
Usage instuctions

### ISSUE THREAD

**Issue by dev-fJ-del** [MenelicSoftware/cordova-plugin-brother-label-printer#4]
Hi @arcadius 
Thanks for the merge earlier, I just want to fund out how can this be used in HTML 5
I've added this on my device-ready, but says method brotherPrinter does not exist..
cordova.plugins.brotherPrinter.printLabel(img, { "numberOfCopies": 1, "orientation": "LANDSCAPE", "labelName": "W62RB", "modelName": "RJ-4040", "port": "NET" })

Thank you

**Comment by arcadius** [comment]
Hi @dev-fJ-del 
At the moment, that single interface thing is not yet merged in 
https://github.com/gordol/cordova-brother-label-printer

For now, It is only available in 
https://github.com/MenelicSoftware/cordova-plugin-brother-label-printer

I am discussing with @gordol ...
We will merge the two forks at some point

**Comment by arcadius** [comment]
There is a sample usage at 
https://github.com/MenelicSoftware/cordova-plugin-brother-label-printer#sample-code

**Comment by arcadius** [comment]
https://github.com/MenelicSoftware/cordova-plugin-brother-label-printer#sample-code
