### ISSUE TITLE
App Crashes with Update

### ISSUE THREAD

**Issue by cpgb85** [MenelicSoftware/cordova-plugin-brother-label-printer#41]
After removing the old plugin and upgrading, i can no longer build my app.  Why the heck don't things just work on iOS? lol

<img width="992" alt="Screen Shot 2021-06-28 at 9 09 19 PM" src="https://user-images.githubusercontent.com/21691341/123726212-2e90e680-d855-11eb-9fa1-f3eb61c5530c.png">

**Comment by arcadius** [comment]
Hello @cpgb85 
Please can you give more detail about the error message.
The screenshot does not show that much

**Comment by cpgb85** [comment]
I actually embeded and signed it and it worked referencing #39 before you even mentioned it.  Great plugin by the way, you are a life saver for not only making this but updating it also :).
