### ISSUE TITLE
Capacitorjs

### ISSUE THREAD

**Issue by kieranbarlow** [MenelicSoftware/cordova-plugin-brother-label-printer#50]
How would I use this in a Ionic Capacitorjs project?

**Comment by arcadius** [comment]
Hello @kieranbarlow .
As per 
https://capacitorjs.com/docs/v2/cordova/using-cordova-plugins

You will need 2 commands

`
npm install cordova-plugin-brother-label-printer

npx cap sync

`

I have not tried this myself as I am still on an old Cordova project... But this should work.

Please let us know the outcome please.

**Comment by kieranbarlow** [comment]
Hey @arcadius, unfortunately I get errors when trying to run npx cap sync

```
Updating iOS native dependencies with pod install - failed!
[capacitor] ✖ update ios - failed!
[capacitor] [error] Analyzing dependencies
```
```

[!] Oh no, an error occurred.
[capacitor]         
[capacitor]         Search for existing GitHub issues similar to yours:
[capacitor]         https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle%2C+0x0009%29%3A+tried%3A+%27%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle%27+%28mach-o+file%2C+but+is+an+incompatible+architecture+%28have+%28x86_64%29%2C+need+%28arm64e%29%29%29+-+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle&type=Issues
```

**Comment by kieranbarlow** [comment]
```
Searching for inspections failed: undefined method `map' for nil:NilClass
[capacitor]         Looking for related issues on cocoapods/cocoapods...

```

**Comment by kieranbarlow** [comment]
`LoadError - dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))) - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle`

**Comment by kieranbarlow** [comment]
I've since tried `arch -x86_64 pod install` but I get the following:

```
- Analyzing dependencies
- Downloading dependencies
- Installing BRLMPrinterKit (4.0.2.1)
- Installing CordovaPluginsStatic (4.0.1)
- [!] The 'Pods-App' target has frameworks with conflicting names: brlmprinterkit.framework.
```

**Comment by kieranbarlow** [comment]
I should add I'm using 

- M1 mac

**Comment by kieranbarlow** [comment]
Closing this issue and raising a new one with better context.
